### ISSUE TITLE
remember feature of pickFile is failure when use preLaunchTask of  launch setup in first time only

### ISSUE THREAD

**Issue by simon8233** [rioj7/command-variable#40] opened 2022-10-11 04:24 UTC
Hi all,

first of all, I very appreciate for command-variable extension. it's very general and useful for VS Code task/debug process uages.

following description is my problems. 

I try to use pickFiles function of command-variable in preLanuchTask to resolve get debug file at debug process starting every time.

In first time of opening workspace. Debug programs will raise 'launch: program  'I don't remember' does not exists'

but, following execution (2rd or 3th choose debug program) is back to normal.

is it have any suggestion to resolve pickFiles failure of preLanuchTask in first time.

""

**Comment by simon8233** [comment] 2022-10-11 06:48
I resolved it with postDebugTask configuration of launch.json

**Comment by rioj7** [comment] 2022-10-13 02:38
@simon8233  without the content of launch and task file it is hard to tell the reason.

If you use a `${remember}` variable but you haven't set the name to remember you get the `I don't remember`

If the problem is solved you can close the issue

**Comment by simon8233** [comment] 2022-10-17 07:10
Thanks for your reply.
I think issue is resolved.

**Closed** 2022-10-17 07:11 UTC
